GET http://localhost:5000/tracks

###
GET http://localhost:5000/tracks/1

###
POST http://localhost:5000/tracks
Content-Type: application/json

{
    "artist": {
        "name": "test",
        "nickname": "test",
        "age": 20
    },
    "album": "test",
    "cover": "test"
}

###
PUT http://localhost:5000/tracks/67adbac2f980f6e84ac74590
Content-Type: application/json

{
    "artist": {
        "name": "test2",
        "nickname": "test",
        "age": 20
    },
    "album": "test",
    "cover": "test"
}

###
DELETE http://localhost:5000/tracks/67adbac2f980f6e84ac74590



