GET http://localhost:5000/tracks
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RiZGMwODhkZjgwOWYwZjFmMzQ4ZDIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQyNDYxOTY2LCJleHAiOjE3NDI0OTc5NjZ9.cflpcx3uX0Ya8QQxjcS46_CCcs5m50IPzpTIckBKc-0

###
GET http://localhost:5000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M5NjFmNmY5ZDI5MGU5MGY0ZmYyNjciLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQxMjUxMjg4LCJleHAiOjE3NDEyODcyODh9.N52M5jUZoDNJllweE1VxW9e-KrGbMRR77Q0dyz6dlr0

###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "name": "test",
    "age": 20,
    "email": "test@gmail.com",
    "role": "admin",
    "password": "1234asdf"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "1234asdf"
}

###
POST http://localhost:5000/tracks
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M5NWJiYjU1NWY2MzQ3OGI3ZTJhYzkiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQxMjUwNTA2LCJleHAiOjE3NDEyODY1MDZ9.-plumJoRMubDStgRLRG_D3n80FhyB_4ZCWgsemcGXpg

{
    "artist": {
        "name": "test",
        "nickname": "test",
        "edad": 20
    },
    "album": "test",
    "cover": "test",
    "mediaId": "67dbdd0e0b383542d9b480c7"
}


###
PUT http://localhost:5000/tracks/67dbdb6500fea86889f90df0
Content-Type: application/json

{
    "artist": {
        "name": "test2",
        "nickname": "test",
        "age": 20
    },
    "album": "test",
    "cover": "test"
}

###
DELETE http://localhost:5000/tracks/67c825201acc906616b3b05b

###
POST http://localhost:5000/storage HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/jpeg

< ./test.jpg
--boundary123--

###
GET http://localhost:5000/test.jpg

